version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Path to backend Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend  # Path to frontend Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents overwriting node_modules with volume
    stdin_open: true
    tty: true
    depends_on:
      - backend  # Ensures frontend starts after backend
